In [14]:
# @hidden_cell
# The project token is an authorization token that is used to access project resources like data sources, connections, and used by platform APIs.
from project_lib import Project
project = Project(project_id='cd79b8ce-d4e8-4ab7-a694-6cfc6d8044a3', project_access_token='p-b900378cb652a49d854c33c09cec5fc5f51e72a1')
pc = project.project_context

In [15]:
import pandas as pd
import numpy as np

our_file = project.get_file("StormEvents_details-ftp_v1.0_d2018_c20200219.csv") # returns BytesIO object from file name
our_df = pd.read_csv(our_file) # parse to a Pandas DataFrame using pd.read_csv()
print(type(our_df))
our_df.head()

<class 'pandas.core.frame.DataFrame'>

,STATE,MONTH_NAME,EVENT_TYPE,CZ_NAME,INJURIES_DIRECT,INJURIES_INDIRECT,total injuries,DEATHS_DIRECT,DEATHS_INDIRECT,total deaths,DAMAGE_PROPERTY,DAMAGE_CROPS,DAMAGE_PROPERTY_FIXED,DAMAGE_CROPS_FIXED,DAMAGE_SUM,OUR_METRIC
0,KENTUCKY,May,Flash Flood,MONTGOMERY,0,0,0,0,0,0,0.00K,0.01K,0,10,10,6.666670e-07
1,KENTUCKY,May,Flash Flood,ROWAN,0,0,0,0,0,0,0.00K,0.01K,0,10,10,6.666670e-07
2,KENTUCKY,May,Flash Flood,ELLIOTT,0,0,0,0,0,0,0.10K,0.00K,100,0,100,6.666670e-06
3,KENTUCKY,May,Flash Flood,WHITLEY,0,0,0,0,0,0,0.10K,0.00K,100,0,100,6.666670e-06
4,MARYLAND,May,Flood,MONTGOMERY,0,0,0,0,0,0,0.10K,0.00K,100,0,100,6.666670e-06

In [16]:
newvalues = []
for row in our_df['OUR_METRIC']:
    if row <= 0.001:
        newvalues.append(1)
    elif row <= 1:
        newvalues.append(2)
    elif row <= 5:
        newvalues.append(3) 
    elif row <= 10:
        newvalues.append(4)
    elif row <= 20:
        newvalues.append(5)
    elif row <= 30:
        newvalues.append(6)
    elif row <= 40:
        newvalues.append(7)
    elif row <= 60:
        newvalues.append(8)
    elif row <= 80:
        newvalues.append(9)
    else:
        newvalues.append(10)
print(newvalues)

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 6, 6, 6, 6, 7, 8, 8, 8, 8, 8, 8, 8, 8, 9, 10, 10]

In [17]:
np_array = np.asarray(newvalues)
our_df['Severity'] = np_array

In [18]:
our_df.head(10000)

,STATE,MONTH_NAME,EVENT_TYPE,CZ_NAME,INJURIES_DIRECT,INJURIES_INDIRECT,total injuries,DEATHS_DIRECT,DEATHS_INDIRECT,total deaths,DAMAGE_PROPERTY,DAMAGE_CROPS,DAMAGE_PROPERTY_FIXED,DAMAGE_CROPS_FIXED,DAMAGE_SUM,OUR_METRIC,Severity
0,KENTUCKY,May,Flash Flood,MONTGOMERY,0,0,0,0,0,0,0.00K,0.01K,0,10,10,6.666670e-07,1
1,KENTUCKY,May,Flash Flood,ROWAN,0,0,0,0,0,0,0.00K,0.01K,0,10,10,6.666670e-07,1
2,KENTUCKY,May,Flash Flood,ELLIOTT,0,0,0,0,0,0,0.10K,0.00K,100,0,100,6.666670e-06,1
3,KENTUCKY,May,Flash Flood,WHITLEY,0,0,0,0,0,0,0.10K,0.00K,100,0,100,6.666670e-06,1
4,MARYLAND,May,Flood,MONTGOMERY,0,0,0,0,0,0,0.10K,0.00K,100,0,100,6.666670e-06,1
5,CALIFORNIA,January,Tornado,HUMBOLDT,0,0,0,0,0,0,0.10K,0.00K,100,0,100,6.666670e-06,1
6,MISSISSIPPI,September,Tornado,MONTGOMERY,0,0,0,0,0,0,0.10K,0.00K,100,0,100,6.666670e-06,1
7,IOWA,May,Tornado,POCAHONTAS,0,0,0,0,0,0,0.00K,0.10K,0,100,100,6.666670e-06,1
8,IOWA,May,Tornado,STORY,0,0,0,0,0,0,0.00K,0.10K,0,100,100,6.666670e-06,1
9,IOWA,June,Tornado,GREENE,0,0,0,0,0,0,0.00K,0.10K,0,100,100,6.666670e-06,1
10,IOWA,June,Tornado,WEBSTER,0,0,0,0,0,0,0.00K,0.10K,0,100,100,6.666670e-06,1
11,IOWA,July,Tornado,MARSHALL,0,0,0,0,0,0,0.00K,0.10K,0,100,100,6.666670e-06,1
12,IOWA,July,Tornado,WRIGHT,0,0,0,0,0,0,0.00K,0.10K,0,100,100,6.666670e-06,1
13,SOUTH CAROLINA,June,Flash Flood,LEXINGTON,0,0,0,0,0,0,0.10K,0.10K,100,100,200,1.333330e-05,1
14,KANSAS,September,Flash Flood,WILSON,0,0,0,0,0,0,0.10K,0.10K,100,100,200,1.333330e-05,1
15,SOUTH CAROLINA,September,Flash Flood,AIKEN,0,0,0,0,0,0,0.10K,0.10K,100,100,200,1.333330e-05,1
16,SOUTH CAROLINA,May,Flash Flood,ORANGEBURG,0,0,0,0,0,0,0.10K,0.10K,100,100,200,1.333330e-05,1
17,SOUTH CAROLINA,May,Flash Flood,ORANGEBURG,0,0,0,0,0,0,0.10K,0.10K,100,100,200,1.333330e-05,1
18,SOUTH CAROLINA,September,Flash Flood,LANCASTER,0,0,0,0,0,0,0.10K,0.10K,100,100,200,1.333330e-05,1
19,SOUTH CAROLINA,September,Flash Flood,LANCASTER,0,0,0,0,0,0,0.10K,0.10K,100,100,200,1.333330e-05,1
20,SOUTH CAROLINA,September,Flash Flood,LANCASTER,0,0,0,0,0,0,0.10K,0.10K,100,100,200,1.333330e-05,1
21,SOUTH CAROLINA,September,Flash Flood,LANCASTER,0,0,0,0,0,0,0.10K,0.10K,100,100,200,1.333330e-05,1
22,SOUTH CAROLINA,September,Flash Flood,LANCASTER,0,0,0,0,0,0,0.10K,0.10K,100,100,200,1.333330e-05,1
23,SOUTH CAROLINA,September,Flash Flood,LANCASTER,0,0,0,0,0,0,0.10K,0.10K,100,100,200,1.333330e-05,1
24,SOUTH CAROLINA,September,Flash Flood,LANCASTER,0,0,0,0,0,0,0.10K,0.10K,100,100,200,1.333330e-05,1
25,SOUTH CAROLINA,September,Flash Flood,LANCASTER,0,0,0,0,0,0,0.10K,0.10K,100,100,200,1.333330e-05,1
26,SOUTH CAROLINA,September,Flash Flood,LANCASTER,0,0,0,0,0,0,0.10K,0.10K,100,100,200,1.333330e-05,1
27,SOUTH CAROLINA,September,Flash Flood,LANCASTER,0,0,0,0,0,0,0.10K,0.10K,100,100,200,1.333330e-05,1
28,SOUTH CAROLINA,September,Flash Flood,CHESTERFIELD,0,0,0,0,0,0,0.10K,0.10K,100,100,200,1.333330e-05,1
29,SOUTH CAROLINA,September,Flash Flood,LANCASTER,0,0,0,0,0,0,0.10K,0.10K,100,100,200,1.333330e-05,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3405,ILLINOIS,December,Tornado,CHRISTIAN,22,0,22,0,0,0,118.90M,0.00K,118900000,0,118900000,7.929600e+00,4
3406,IOWA,July,Tornado,MARION,13,0,13,0,0,0,120.00M,4.50K,120000000,4500,120004500,8.002033e+00,4
3407,FLORIDA,October,Hurricane,INLAND FRANKLIN,0,0,0,0,0,0,0.00K,150.00M,0,150000000,150000000,1.000000e+01,4
3408,FLORIDA,October,Storm Surge/Tide,COASTAL FRANKLIN,0,0,0,0,0,0,150.00M,0.00K,150000000,0,150000000,1.000000e+01,4
3409,FLORIDA,October,Hurricane,COASTAL FRANKLIN,0,0,0,0,1,1,150.00M,0.00K,150000000,0,150000000,1.000067e+01,5
3410,FLORIDA,October,Hurricane,LEON,0,0,0,0,1,1,100.00M,50.00M,100000000,50000000,150000000,1.000067e+01,5
3411,GEORGIA,October,Hurricane,GRADY,0,0,0,0,0,0,50.00M,111.00M,50000000,111000000,161000000,1.073333e+01,5
3412,GEORGIA,October,Hurricane,BAKER,0,0,0,0,0,0,50.00M,111.00M,50000000,111000000,161000000,1.073333e+01,5
3413,GEORGIA,October,Hurricane,MITCHELL,0,0,0,0,0,0,50.00M,111.00M,50000000,111000000,161000000,1.073333e+01,5
3414,GEORGIA,October,Hurricane,CALHOUN,0,0,0,0,0,0,50.00M,111.00M,50000000,111000000,161000000,1.073333e+01,5
3415,IOWA,July,Tornado,MARSHALL,22,1,23,0,0,0,200.00M,4.00K,200000000,4000,200004000,1.333667e+01,5
3416,FLORIDA,October,Hurricane,INLAND GULF,0,0,0,0,0,0,100.00M,150.00M,100000000,150000000,250000000,1.666667e+01,5
3417,FLORIDA,October,Hurricane,INLAND WAKULLA,0,0,0,0,0,0,100.00M,150.00M,100000000,150000000,250000000,1.666667e+01,5
3418,NORTH CAROLINA,September,Hurricane,INLAND PENDER,0,0,0,0,0,0,300.00M,0.00K,300000000,0,300000000,2.000000e+01,5
3419,FLORIDA,October,Hurricane,COASTAL BAY,0,0,0,0,16,16,300.00M,0.00K,300000000,0,300000000,2.001067e+01,6
3420,FLORIDA,October,Hurricane,INLAND BAY,0,0,0,0,0,0,200.00M,150.00M,200000000,150000000,350000000,2.333333e+01,6
3421,FLORIDA,October,Hurricane,WASHINGTON,0,0,0,0,4,4,250.00M,150.00M,250000000,150000000,400000000,2.666933e+01,6
3422,GEORGIA,October,Hurricane,DOUGHERTY,0,0,0,0,0,0,300.00M,111.00M,300000000,111000000,411000000,2.740000e+01,6
3423,FLORIDA,October,Hurricane,GADSDEN,0,0,0,1,1,2,300.00M,150.00M,300000000,150000000,450000000,3.000133e+01,7
3424,FLORIDA,October,Hurricane,LIBERTY,0,0,0,0,2,2,450.00M,150.00M,450000000,150000000,600000000,4.000133e+01,8
3425,GEORGIA,October,Hurricane,EARLY,0,0,0,0,0,0,150.00M,500.00M,150000000,500000000,650000000,4.333333e+01,8
3426,FLORIDA,October,Hurricane,JACKSON,0,0,0,1,3,4,500.00M,150.00M,500000000,150000000,650000000,4.333600e+01,8
3427,FLORIDA,October,Storm Surge/Tide,COASTAL BAY,0,0,0,6,0,6,700.00M,0.00K,700000000,0,700000000,4.667067e+01,8
3428,GEORGIA,October,Hurricane,MILLER,0,0,0,0,0,0,250.00M,500.00M,250000000,500000000,750000000,5.000000e+01,8
3429,FLORIDA,October,Hurricane,CALHOUN,0,0,0,0,1,1,500.00M,250.00M,500000000,250000000,750000000,5.000067e+01,8
3430,GEORGIA,October,Hurricane,DECATUR,0,0,0,0,0,0,300.00M,500.00M,300000000,500000000,800000000,5.333333e+01,8
3431,GEORGIA,October,Hurricane,SEMINOLE,0,0,0,1,0,1,300.00M,500.00M,300000000,500000000,800000000,5.333400e+01,8
3432,NORTH CAROLINA,September,Hurricane,INLAND NEW HANOVER,1,0,1,0,0,0,1.00B,0.00K,1000000000,0,1000000000,6.666680e+01,9
3433,CALIFORNIA,July,Wildfire,NORTHERN SACRAMENTO VALLEY,0,0,0,2,2,4,1.50B,NaN,1500000000,0,1500000000,1.000027e+02,10
3434,CALIFORNIA,November,Wildfire,NORTHEAST FOOTHILLS/SACRAMENTO VALLEY,12,0,12,86,0,86,17.00B,0.00K,17000000000,0,17000000000,1.133392e+03,10

In [19]:
new_df = our_df.drop(columns=['INJURIES_DIRECT', 'INJURIES_INDIRECT', 'total injuries', 'DEATHS_DIRECT', 'DEATHS_INDIRECT', 'total deaths', 'DAMAGE_PROPERTY', 'DAMAGE_CROPS', 'DAMAGE_PROPERTY_FIXED', 'DAMAGE_CROPS_FIXED', 'DAMAGE_SUM', 'OUR_METRIC'])

In [20]:
new_df.head()

      STATE MONTH_NAME   EVENT_TYPE     CZ_NAME  Severity
0  KENTUCKY        May  Flash Flood  MONTGOMERY         1
1  KENTUCKY        May  Flash Flood       ROWAN         1
2  KENTUCKY        May  Flash Flood     ELLIOTT         1
3  KENTUCKY        May  Flash Flood     WHITLEY         1
4  MARYLAND        May        Flood  MONTGOMERY         1

In [21]:
project.save_data(file_name = "testomg2.csv",data = new_df.to_csv(index=False), overwrite=True)

{'file_name': 'testomg2.csv',
 'message': 'File saved to project storage.',
 'bucket_name': 'firstprojectcomp488-donotdelete-pr-a9l4ct181wq7wr',
 'asset_id': '7e2cb775-492d-48e5-8e2f-3560150ec1eb'}

In [22]:
alabama_df = new_df[new_df['STATE'].str.contains('ALA')]
alabama_df.head()

        STATE MONTH_NAME   EVENT_TYPE  CZ_NAME  Severity
573   ALABAMA      April      Tornado     DALE         1
1196  ALABAMA   February        Flood  HOUSTON         1
1266  ALABAMA       June      Tornado  CULLMAN         1
1312  ALABAMA      March      Tornado  CALHOUN         1
1508  ALABAMA  September  Flash Flood   CLARKE         1

In [23]:
project.save_data(file_name = "alabama.csv",data = alabama_df.to_csv(index=False), overwrite=True)

{'file_name': 'alabama.csv',
 'message': 'File saved to project storage.',
 'bucket_name': 'firstprojectcomp488-donotdelete-pr-a9l4ct181wq7wr',
 'asset_id': '39232e54-505f-4c05-a042-2fca132f8c69'}